/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TButton: typeof import('tdesign-vue-next')['Button']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTagInput: typeof import('tdesign-vue-next')['TagInput']
  }
}
